runtime: custom
env: flex

# Automatic scaling configuration
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cpu_utilization:
    target_utilization: 0.6

# Resources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Health check - use root path for better compatibility
readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/api/auth/status"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Environment variables (set these in App Engine settings or via gcloud)
env_variables:
  NODE_ENV: production
  PORT: 8080

# Note: DATABASE_URL and SESSION_SECRET should be set via:
# gcloud app deploy --set-env-vars DATABASE_URL=...,SESSION_SECRET=...
# Or in App Engine Console → Settings → Environment Variables

